services:
  db:
    image: mysql
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password1234
      MYSQL_DATABASE: spring_test
  backend:
    build: .
    restart: on-failure
    depends_on:
      - db
    ports:
      - "8100:8080"

